## chapter 02

In [90]:
# 导入numpy
from numpy import *

In [91]:
# 创建数组
arr = array([[1, 1], [0, 1], [0, 0]])
arr

array([[1, 1],
       [0, 1],
       [0, 0]])

In [92]:
# 获取数组的行数
arr.shape[0]

3

In [93]:
# 是将原矩阵横向、纵向地复制
# 见：https://www.jianshu.com/p/9519f1984c70

# 行复制两次，列复制一次
tile(arr, (2, 1))

array([[1, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [0, 0]])

In [94]:
# 行复制两次，列复制一次
tile(arr, (2, 2))

array([[1, 1, 1, 1],
       [0, 1, 0, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 1, 0, 1],
       [0, 0, 0, 0]])

In [95]:
# 返回数组值从小到大所对应的下标
arr = array([[2, 3, 4], [4, 2, 3], [4, 5, 6]])
arr.argsort()

array([[0, 1, 2],
       [1, 2, 0],
       [0, 1, 2]])

In [96]:
# 字典获取指定的值
d = {'a': 1, 'b': 2, 'c': 3}
d.get('b')

2

In [97]:
# 指定默认值
print(d.get('d', None))

None


In [98]:
# 创建m行n列的全0矩阵
zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [99]:
# 获取index行的数据
# arr[index, :]
arr[1, :]

array([4, 2, 3])

In [100]:
# 获取每列的最小值
arr.min(0)

array([2, 2, 3])

In [101]:
# 获取每列的最大值
arr.max(0)

array([4, 5, 6])

In [102]:
# m行到n行的数据
# arr[m:n, :]
# arr = array([[2, 3, 4], [4, 2, 3], [4, 5, 6]])
arr[1:3, :]

array([[4, 2, 3],
       [4, 5, 6]])