## chapter 02

In [84]:
# 导入numpy
from numpy import *

In [85]:
# 创建数组
arr = array([[1, 1], [0, 1], [0, 0]])
arr

array([[1, 1],
       [0, 1],
       [0, 0]])

In [86]:
# 获取数组的行数
arr.shape[0]

3

In [87]:
# 是将原矩阵横向、纵向地复制
# 见：https://www.jianshu.com/p/9519f1984c70

# 行复制两次，列复制一次
tile(arr, (2, 1))

array([[1, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [0, 0]])

In [88]:
# 行复制两次，列复制一次
tile(arr, (2, 2))

array([[1, 1, 1, 1],
       [0, 1, 0, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 1, 0, 1],
       [0, 0, 0, 0]])

In [89]:
# 返回数组值从小到大所对应的下标
arr = array([[2, 3, 4], [4, 2, 3], [4, 5, 6]])
arr.argsort()

array([[0, 1, 2],
       [1, 2, 0],
       [0, 1, 2]])

In [90]:
# 字典获取指定的值
d = {'a': 1, 'b': 2, 'c': 3}
d.get('b')

2

In [91]:
# 指定默认值
print(d.get('d', None))

None


In [92]:
# 创建m行n列的全0矩阵
zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
# 获取index行的数据
# arr[index, :]
arr[1, :]

array([4, 2, 3])

In [94]:
# 获取每列的最小值
arr.min(0)

array([2, 2, 3])

In [95]:
# 获取每列的最大值
arr.max(0)

array([4, 5, 6])

In [96]:
# m行到n行的数据
# arr[m:n, :]
# arr = array([[2, 3, 4], [4, 2, 3], [4, 5, 6]])
arr[1:3, :]

array([[4, 2, 3],
       [4, 5, 6]])

## chapter03

In [97]:
# append与extend的区别
a = [1, 2, 3]
b = [4, 5, 6]
a.append(b)
a

[1, 2, 3, [4, 5, 6]]

In [98]:
a = [1, 2, 3]
b = [4, 5, 6]
a.extend(b)
a

[1, 2, 3, 4, 5, 6]

In [99]:
# 列表推导式

In [100]:
dataSet = [
        [1, 1, 'yes'],
        [1, 1, 'yes'],
        [1, 0, 'no'],
        [0, 1, 'no'],
        [0, 1, 'no']
    ]

for i in range(3):
    arr = [example[i] for example in dataSet]
    print(arr)

[1, 1, 1, 0, 0]
[1, 1, 0, 1, 1]
['yes', 'yes', 'no', 'no', 'no']


In [101]:
# set()函数，会去除重复值
arr = [1, 2, 2, 3]
set(arr)


{1, 2, 3}

In [102]:
import operator

arr = [1, 2, 4, 3, 5]
# 定义一个函数，获取对象第二个域的值
get = operator.itemgetter(1)
print(get(arr))

2


In [103]:
# items()返回可遍历的(键, 值) 元组数组，类似Java中的Map.Entry
dic = {'a': 1, 'b': 2, 'e': 2, 'c': 3, 'd': 4}
dic.items()

dict_items([('a', 1), ('b', 2), ('e', 2), ('c', 3), ('d', 4)])

In [104]:
# sorted(iterable, cmp=None, key=None, reverse=False) 对所有可迭代的对象进行排序操作
#iterable -- 可迭代对象。
# cmp -- 比较的函数，这个具有两个参数，参数的值都是从可迭代对象中取出，此函数必须遵守的规则为，大于则返回1，小于则返回-1，等于则返回0。
# key -- 主要是用来进行比较的元素，只有一个参数，具体的函数的参数就是取自于可迭代对象中，指定可迭代对象中的一个元素来进行排序。
# reverse -- 排序规则，reverse = True 降序 ， reverse = False 升序（默认）。
sortedDic = sorted(dic.items(),
                              key=operator.itemgetter(1),
                              reverse=True)
sortedDic

[('d', 4), ('c', 3), ('b', 2), ('e', 2), ('a', 1)]

In [108]:
# count() 方法用于统计某个元素在列表中出现的次数
arr = [1, 2, 2, 3]
arr.count(2)

2